/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[15],{376:function(ha,ca,f){function ba(e,f,h){f.endsWith("/")||(f+="/");h=h||{};var n=h.disableWebsockets||!1;this.WU=h.singleServerMode||!1;null!=h.customQueryParameters&&Object(y.b)("wvsQueryParameters",h.customQueryParameters);f.endsWith("blackbox/")||(f+="blackbox/");this.tn=h.uploadData||null;this.Kw=h.uriData||null;this.KN=h.cacheKey||null;this.aS=h.officeLocale||null;this.RE=Object(w.a)(f,null,n);this.bg=f;this.gF=e;this.yf=
null;this.Ij=aa();this.jm=aa();this.Ty=!1;this.og=this.Ud=this.oe=this.bf=null;this.Ef=[];this.Dz=[];this.cache={};this.timeStamp=0;this.Xf=[];this.th=[];this.CF=null;this.$E=!1;this.YI=this.id=null;this.CH=this.EQ=fa;this.LB=0;this.FG=!1;this.E9=1;this.QA={};this.As(!0)}function aa(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,Jr:function(){return 1===(e.state&1)},A8:function(){return 2===(e.state&2)},ii:function(){return!e.A8()&&!e.Jr()},g8:function(){return 4===
(e.state&4)},oU:function(){e.state|=4}};e.promise=new Promise(function(f,h){e.resolve=function(){if(0===e.state||4===e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function fa(){return!1}function ea(e,f,h){if(!(f in n))return!0;f=n[f];for(var r=0;r<f.length;r++){var w=e;var x=f[r];var y=h;if(x.name in w){var z="",aa=!1;w=w[x.name];switch(x.type){case "s":z="String";aa=Object(da.isString)(w);
break;case "a":z="Array";aa=Object(da.isArray)(w);break;case "n":z="Number";aa=Object(da.isNumber)(w)&&Object(da.isFinite)(w);break;case "o":z="Object",aa=Object(da.isObject)(w)&&!Object(da.isArray)(w)}aa||y.reject('Expected response field "'+x.name+'" to have type '+z);x=aa}else y.reject('Response missing field "'+x.name+'"'),x=!1;if(!x)return!1}return!0}f.r(ca);var da=f(0);f.n(da);var z=f(1);ha=f(44);var x=f(31),w=f(394),e=f(78),h=f(320),r=f(97),y=f(40),ia=f(141),n={pages:[{name:"pages",type:"a"}],
pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}]};ba.prototype=Object(da.extend)(ba.prototype,{d2:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;
n.open("GET",e.bg+"ck");n.withCredentials=e.Vo();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};n.send()})},Yca:function(e,f){this.EQ=e||fa;this.CH=f||fa},$N:function(){var e=this;this.jm=aa();this.Ij=aa();return this.RE.sF().then(function(){e.Ty=!1;e.id=null;e.$E=!1;return e.d2()})},KI:function(){this.EQ();this.XG();this.bf&&(this.bf.ii()?this.zf(this.bf.request):this.bf.Jr()&&this.CH(this.bf.result.url,"pdf")&&(this.bf=null,this.MT()));this.og&&this.og.ii()&&
this.zf(this.og.request);this.oe&&this.oe.ii()?this.zf(this.oe.request):this.Ud&&this.Ud.ii()&&this.tQ(this.Ud.request);var e;for(e=0;e<this.Xf.length;e++)this.Xf[e]&&this.Xf[e]&&(this.Xf[e].ii()?this.zf(this.Xf[e].request):this.Xf[e].Jr()&&this.CH(this.Xf[e].result.url,"image")&&(this.Xf[e]=null,this.IB(e)));for(e=0;e<this.th.length;e++)this.th[e]&&this.th[e]&&this.th[e].ii()&&!this.th[e].g8()&&this.zf(this.th[e].request);for(e=0;e<this.Ef.length;e++)this.Ef[e]&&this.Ef[e].ii()&&this.zf(this.Ef[e].request)},
XG:function(e){var f=this;this.Ty||(this.timeStamp=Date.now(),this.RE.FJ(function(e){f.S9(e)},function(){return null},function(){return null},!0).then(function(){clearInterval(f.zB);f.zB=null},function(h){f.Ty=!1;if(!f.zB){var n=0;f.$E=!0;f.YI=0;f.zB=setInterval(function(){2>n++?f.KI():(clearInterval(f.zB),e&&e.reject(r.a),Object(z.f)("WebViewerServer connection failed:"+h))},5E3)}}),this.Ty=!0)},gfa:function(){var e=this,f=createPromiseCapability();if(this.tn){var h=new FormData;h.append("file",
this.tn.fileHandle,this.tn.fileHandle.name);var n=this.tn.loadCallback;var r="upload";var w=this.tn.extension}else if(this.Kw){h={uri:this.Kw.uri,Xia:this.Kw.shareId};h=Object.keys(h).map(function(e){return e+"="+(h[e]?encodeURIComponent(h[e]):"")}).join("&");var y="application/x-www-form-urlencoded; charset=UTF-8";n=this.Kw.loadCallback;r="url";w=this.Kw.extension}else return Promise.resolve();var z=new XMLHttpRequest,aa=Object(x.i)(e.bg,"AuxUpload");aa=Object(ia.a)(aa)+"&type="+r+"&ext="+w;z.open("POST",
aa);z.withCredentials=this.Vo();y&&z.setRequestHeader("Content-Type",y);z.addEventListener("load",function(){if(z.readyState===z.DONE&&200===z.status){var h=JSON.parse(z.response);e.gF=h.uri;n(h);f.resolve(h)}});z.addEventListener("error",function(){f.reject(z.statusText+" "+JSON.stringify(z))});this.tn&&null!=this.tn.onProgress&&(z.upload.onprogress=function(f){e.tn.onProgress(f)});z.send(h);return f.promise},Gba:function(e){this.password=e||null;this.Ij.Jr()||(this.Ij=aa(),this.zf({t:"pages"}));
return this.Ij.promise},ew:function(e){this.CF=e||null;this.Ij.Jr()||(this.XG(this.Ij),this.zf({t:"pages"}));return this.Ij.promise},cO:function(e){e=Object.assign(e,{uri:encodeURIComponent(this.gF)});this.CF&&(e.ext=this.CF);this.yf&&(e.c=this.yf);this.password&&(e.pswd=this.password);this.KN&&(e.cacheKey=this.KN);this.aS&&(e.locale=this.aS);return e},zf:function(e){e=this.cO(e);this.RE.send(e)},xk:function(e){return e},S9:function(f){var h=this,n=f.data,r=f.err,w=f.t;switch(w){case "upload":r?h.hfa.reject(r):
h.hfa.resolve("Success");break;case "pages":r?h.Ij.reject(r):ea(n,w,h.Ij)&&h.Ij.resolve(n);break;case "config":r?h.jm.reject(r):ea(n,w,h.jm)&&(n.id&&(h.id=n.id),n.auth&&(f=Object(y.a)("wvsQueryParameters"),f.auth=n.auth,Object(y.b)("wvsQueryParameters",f)),n.serverVersion&&(h.Dfa=n.serverVersion,Object(z.g)("[WebViewer Server] server version: "+h.Dfa)),n.serverID?(h.LB=n.serverID===h.YI&&h.FG?h.LB+1:0,h.YI=n.serverID):h.LB=0,h.FG=!1,h.jm.resolve(n));break;case "health":r?h.jm.reject(r):ea(n,w,h.jm)&&
(n=n.unhealthy,h.WU&&n?Object(z.i)("Server failed health check. Single server mode ignoring check."):!h.sha&&n&&1>=h.LB&&(h.FG=!0,h.$N().then(function(){h.KI()},function(){h.KI()})));break;case "pdf":n.url=Object(ia.a)(h.bg+"../"+encodeURI(n.url));r?h.bf.reject(r):ea(n,w,h.bf)&&h.bf.resolve(n);break;case "docmod":n.url=Object(ia.a)(h.bg+"../"+encodeURI(n.url));r?h.QA[n.rID].reject(r):ea(n,w,h.bf)&&h.QA[n.rID].resolve(n);break;case "xod":if(r)this.oe&&this.oe.ii()&&this.oe.reject(r),this.Ud&&this.Ud.ii()&&
this.Ud.reject(r);else if(n.notFound)n.noCreate||this.oe&&this.oe.ii()&&this.oe.resolve(n),this.Ud&&this.Ud.ii()&&this.Ud.resolve(n);else{n.url&&(n.url=Object(ia.a)(h.bg+"../"+encodeURI(n.url)));if(!this.Ud||this.Ud.Jr())this.Ud=aa(),this.Ud.request={t:"xod",noCreate:!0};this.oe||(this.oe=aa(),this.oe.request={t:"xod"});this.Ud.resolve(n);this.oe.resolve(n)}break;case "annots":if(r)h.og.reject(r);else if(ea(n,w,h.og)){h.og.oU();var x=new XMLHttpRequest;f=h.bg+"../"+encodeURI(n.url);var ba=n.hasAppearance?
Object(ia.a)(f+".xodapp"):null;x.open("GET",Object(ia.a)(f));x.responseType="text";x.withCredentials=this.Vo();x.addEventListener("load",function(){x.readyState===x.DONE&&200===x.status&&h.og.resolve({aK:x.response,tN:ba})});x.addEventListener("error",function(){h.og.reject(x.statusText+" "+JSON.stringify(x))});x.send()}break;case "image":var da=this.Xf[n.p];r?da.promise.reject(r):ea(n,w,da)&&(da.result=n,da.result.url=Object(ia.a)(h.bg+"../"+encodeURI(da.result.url)),da.resolve(da.result));break;
case "tiles":da=n.rID;f=this.Ef[da];this.Ef[da]=null;this.Dz.push(da);if(r)f.reject(r);else if(ea(n,w,f)){for(r=0;r<n.tiles.length;r++)n.tiles[r]=Object(ia.a)(h.bg+"../"+encodeURI(n.tiles[r]));f.resolve(n)}break;case "text":da=this.th[n.p];if(r)da.reject(r);else if(ea(n,w,da)){da.oU();var ca=new XMLHttpRequest;n=Object(ia.a)(h.bg+"../"+encodeURI(n.url));ca.open("GET",n);ca.withCredentials=this.Vo();ca.addEventListener("load",function(){ca.readyState===ca.DONE&&200===ca.status&&(da.result=JSON.parse(ca.response),
da.resolve(da.result))});ca.addEventListener("error",function(e){da.reject(ca.statusText+" "+JSON.stringify(e))});ca.send()}break;case "progress":"loading"===n.t&&h.trigger(e.a.Events.DOCUMENT_LOADING_PROGRESS,[n.bytes,n.total])}},BP:function(){this.XG(this.jm);return this.jm.promise},k5:function(){this.og||(this.og=aa(),this.og.request={t:"annots"},this.zf(this.og.request));return this.og.promise},IB:function(e){this.Xf[e]||(this.Xf[e]=aa(),this.Xf[e].request={t:"image",p:e},this.zf(this.Xf[e].request));
return this.Xf[e].promise},Hba:function(e){this.th[e]||(this.th[e]=aa(),this.th[e].request={t:"text",p:e},this.zf(this.th[e].request));return this.th[e].promise},Iba:function(e,f,h,n){var r=this.Ef.length;this.Dz.length&&(r=this.Dz.pop());this.Ef[r]=aa();this.Ef[r].request={t:"tiles",p:e,z:f,r:h,size:n,rID:r};this.zf(this.Ef[r].request);return this.Ef[r].promise},MT:function(){this.bf||(this.bf=aa(),this.bf.request={t:"pdf"},this.$E?this.bf.resolve({url:this.gF}):this.zf(this.bf.request));return this.bf.promise},
TP:function(e){var f=this,h=new XMLHttpRequest,n=Object(ia.a)(this.bg+"aul")+"&id="+this.id,r=new FormData,w={};e.annots&&(w.annots="xfdf");e.watermark&&(w.watermark="png");e.redactions&&(w.redactions="redact");w={t:"docmod",reqID:this.E9++,parts:w};e.print&&(w.print=!0);var x=this.cO(w);r.append("msg",JSON.stringify(x));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var w=e[0],y=e[1],z=e[2];w&&r.append("annots",w);y&&r.append("watermark",
e.watermark);z&&r.append("redactions",z);f.QA[x.reqID]=aa();h.open("POST",n);h.withCredentials=f.Vo;e=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down annotation data to the server"))}});h.send(r);return e.then(function(){return f.QA[x.reqID].promise})})},tQ:function(){this.Ud||(this.Ud=aa(),this.Ud.request={t:"xod",noCreate:!0},this.zf(this.Ud.request));return this.Ud.promise},Jba:function(){this.oe||(this.oe=
aa(),this.oe.request={t:"xod"},this.zf(this.oe.request));return this.oe.promise},an:function(){return!0},request:function(){},eT:function(){},abort:function(){for(var e=0;e<this.Ef.length;e++)this.Ef[e]&&(this.Ef[e].resolve(null),this.Ef[e]=null,this.Dz.push(e));this.close()},TB:function(e){this.yf=this.yf||{};this.yf.headers=e},Pha:function(){return this.yf?Object(da.omit)(this.yf.headers,["Cookie","cookie"]):null},As:function(e){this.yf=this.yf||{};this.yf.internal=this.yf.internal||{};this.yf.internal.withCredentials=
e},Vo:function(){return this.yf&&this.yf.internal?this.yf.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ha.a)(ba);Object(h.a)(ba);Object(h.b)(ba);ca["default"]=ba},394:function(ha,ca,f){function ba(f,x,w){function e(e,f){function h(e){r().then(function(f){ba&&!ca?setTimeout(function(){h(e)},1):f.send(JSON.stringify(e))})}function n(e,f,n,r){var ia=window.createPromiseCapability(),ja=!1,ka=ia;y=e;z=f;aa=n;x=null;r&&(e=Object(ea.a)("wvsQueryParameters"),e.bcid=
Object(fa.j)(8),Object(ea.b)("wvsQueryParameters",e));try{e=ha?ma+"/"+ha:ma+"/ws";e=Object(da.a)(e);var la=new WebSocket(e);la.onopen=function(){ia.resolve();ja=!0;ia=null;ba=!1;w.resolve(la);z&&z()};la.onerror=function(e){ba=ca=!0;ia&&ia.reject(e);x&&x.reject()};la.onclose=function(){w=window.createPromiseCapability();ba=!0;x||(x=window.createPromiseCapability());x.resolve();aa&&aa();y&&ja&&y({t:"health",data:{unhealthy:!0,isDead:!0}})};la.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?
h({hb:!0}):e.end?close():y(e))}}catch(Ea){ia.reject(Ea),ia=null}return ka.promise}function r(){ba&&y&&n(y);return w.promise}var w=window.createPromiseCapability(),x=null,y,z,aa=null,ba=!1,ca=!1,ha=f,ma=function(e){var f=e.indexOf("://"),h="ws://";0>f?f=0:(5===f&&(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return h+e.slice(f,n)}(e);return{send:h,FJ:n,sF:function(){return x?x.promise:r().then(function(e){x=window.createPromiseCapability();y=null;e.close();return x.promise})}}}function h(e){var f=
e.lastIndexOf("/");0>f&&(f=e.length);return e.slice(0,f)}return window.WebSocket&&!w?e(f,x):function(e,f){function r(e){(ea?ea.promise:Promise.resolve(ba)).then(function(f){var h=new XMLHttpRequest,n=z?y+"/"+z+"pf":y+"/pf";n=Object(da.a)(n)+"&id="+f;f=new FormData;f.append("data",JSON.stringify(e));h.open("POST",n);h.withCredentials=!0;h.send(f)})}function n(){ba=0;ea||(ea=window.createPromiseCapability())}function w(){x=new XMLHttpRequest;var e=y+"/pf";e+=0!==ba?"?id="+ba+"&uc="+ma:"?uc="+ma;ma++;
x.open("GET",e,!0);x.withCredentials=!0;x.setRequestHeader("Cache-Control","no-cache");x.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=x,h=!1;x.onreadystatechange=function(){a:if(3<=f.readyState&&!h){try{var e=f.responseText.length}catch(Da){Object(aa.g)("caught exception");break a}if(0<e)try{var x=f.responseText.split("\n");for(x[x.length-1]&&x.pop();0<x.length&&3>x[x.length-1].length;)"]"===x.pop()&&n();0<x.length&&3>x[0].length&&x.shift();for(e=0;e<x.length;++e)x[e].endsWith(",")&&
(x[e]=x[e].substr(0,x[e].length-1));0===ba&&0<x.length&&(ba=JSON.parse(x.shift()).id,e=ea,ea=null,e.resolve(ba));var y;for(e=0;e<x.length;++e)(y=JSON.parse(x[e]))&&y.end?close():y&&y.hb&&y.id===ba?r({hb:!0}):ha(y)}catch(Da){}ca||(h=!0,w())}};x.send()}var x,y=h(e),z=f,ba=0,ea=window.createPromiseCapability(),ca=!1,fa=null,ha=null,ma=0;return{send:r,FJ:function(e,f,h){ha=e;fa=h;ca=!1;n();w();f&&f();return Promise.resolve()},sF:function(){n();ha=null;ca=!0;fa&&fa();x.abort();return Promise.resolve()}}}(f,
x)}f.d(ca,"a",function(){return ba});var aa=f(1),fa=f(31),ea=f(40),da=f(141)}}]);}).call(this || window)
