/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{381:function(ha,ca,f){f.r(ca);var ba=f(2),aa=f(406),fa=f(407),ea;(function(f){f[f.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";f[f.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";f[f.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ea||(ea={}));ha=function(){function f(f){this.V=f;this.state=ea.EXTERNAL_XFDF_NOT_REQUESTED}f.prototype.g7=function(){var f=this;return function(x,w,e){return Object(ba.b)(f,
void 0,void 0,function(){var f,r,y,z,n,aa,da,ca=this,fa;return Object(ba.d)(this,function(h){switch(h.label){case 0:if(this.state!==ea.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];f=this.V.getDocument().fr();return[4,this.H5(f)];case 1:r=h.ia(),y=this.s1(r),this.xF=null!==(fa=null===y||void 0===y?void 0:y.parse())&&void 0!==fa?fa:null,this.state=null===this.xF?ea.EXTERNAL_XFDF_NOT_AVAILABLE:ea.EXTERNAL_XFDF_AVAILABLE,h.label=2;case 2:if(this.state===ea.EXTERNAL_XFDF_NOT_AVAILABLE)return e(x),[2];z=new DOMParser;
n=z.parseFromString(x,"text/xml");w.forEach(function(e){ca.merge(n,ca.xF,e-1)});aa=new XMLSerializer;da=aa.serializeToString(n);e(da);return[2]}})})}};f.prototype.bJ=function(f){this.H5=f};f.prototype.be=function(){this.xF=void 0;this.state=ea.EXTERNAL_XFDF_NOT_REQUESTED};f.prototype.s1=function(f){return f?Array.isArray(f)?new aa.a(f):"string"!==typeof f?null:(new DOMParser).parseFromString(f,"text/xml").querySelector("xfdf > add")?new aa.a(f):new fa.a(f):null};f.prototype.merge=function(f,x,w){var e=
this;0===w&&(this.o9(f,x.fo),this.q9(f,x.hF));var h=x.ca[w];h&&(this.r9(f,h.$l),this.t9(f,h.VV,x.zu),this.s9(f,h.page,w),this.p9(f,h.zO));h=this.V.Oc();if(w===h-1){var r=x.zu;Object.keys(r).forEach(function(h){r[h].IG||e.NR(f,h,r[h])})}};f.prototype.o9=function(f,x){null!==x&&(f=this.St(f),this.wp(f,"calculation-order",x))};f.prototype.q9=function(f,x){null!==x&&(f=this.St(f),this.wp(f,"document-actions",x))};f.prototype.r9=function(f,x){var w=this,e=this.Rt(f.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(f){w.wp(e,
'[name="'+f+'"]',x[f])})};f.prototype.t9=function(f,x,w){var e=this;if(0!==x.length){var h=this.St(f);x.forEach(function(r){var x=r.getAttribute("field"),z=w[x];z&&(e.NR(f,x,z),e.wp(h,"null",r))})}};f.prototype.NR=function(f,x,w){var e=this.St(f);null!==w.yz&&this.wp(e,'ffield [name="'+x+'"]',w.yz);f=this.Rt(f.querySelector("xfdf"),"fields");x=x.split(".");this.rI(f,x,0,w.value);w.IG=!0};f.prototype.s9=function(f,x,w){null!==x&&(f=this.St(f),f=this.Rt(f,"pages"),this.wp(f,'[number="'+(w+1)+'"]',x))};
f.prototype.p9=function(f,x){Object.keys(x).forEach(function(w){(w=f.querySelector('annots [name="'+w+'"]'))&&w.parentElement.removeChild(w)})};f.prototype.rI=function(f,x,w,e){if(w===x.length)x=document.createElementNS("","value"),x.textContent=e,this.wp(f,"value",x);else{var h=x[w];this.Rt(f,'[name="'+h+'"]',"field").setAttribute("name",h);f=f.querySelectorAll('[name="'+h+'"]');1===f.length?this.rI(f[0],x,w+1,e):(h=this.H4(f),this.rI(w===x.length-1?h:this.Dea(f,h),x,w+1,e))}};f.prototype.H4=function(f){for(var x=
null,w=0;w<f.length;w++){var e=f[w];if(0===e.childElementCount||1===e.childElementCount&&"value"===e.children[0].tagName){x=e;break}}return x};f.prototype.Dea=function(f,x){for(var w=0;w<f.length;w++)if(f[w]!==x)return f[w];return null};f.prototype.wp=function(f,x,w){x=f.querySelector(x);null!==x&&f.removeChild(x);f.appendChild(w)};f.prototype.St=function(f){var x=f.querySelector("pdf-info");if(null!==x)return x;x=this.Rt(f.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");
x.setAttribute("version","2");x.setAttribute("import-version","3");return x};f.prototype.Rt=function(f,x,w){var e=f.querySelector(x);if(null!==e)return e;e=document.createElementNS("",w||x);f.appendChild(e);return e};return f}();ca["default"]=ha},392:function(ha,ca){ha=function(){function f(){}f.prototype.ey=function(f){var aa={fo:null,hF:null,zu:{},ca:{}};f=(new DOMParser).parseFromString(f,"text/xml");aa.fo=f.querySelector("pdf-info calculation-order");aa.hF=f.querySelector("pdf-info document-actions");
aa.zu=this.m$(f);aa.ca=this.y$(f);return aa};f.prototype.m$=function(f){var aa=f.querySelector("fields");f=f.querySelectorAll("pdf-info > ffield");if(null===aa&&null===f)return{};var ba={};this.f_(ba,aa);this.d_(ba,f);return ba};f.prototype.f_=function(f,aa){if(null!==aa&&aa.children){for(var ba=[],ca=0;ca<aa.children.length;ca++){var da=aa.children[ca];ba.push({name:da.getAttribute("name"),element:da})}for(;0!==ba.length;)for(aa=ba.shift(),ca=0;ca<aa.element.children.length;ca++)da=aa.element.children[ca],
"value"===da.tagName?f[aa.name]={value:da.textContent,yz:null,IG:!1}:da.children&&ba.push({name:aa.name+"."+da.getAttribute("name"),element:da})}};f.prototype.d_=function(f,aa){aa.forEach(function(aa){var ba=aa.getAttribute("name");f[ba]?f[ba].yz=aa:f[ba]={value:null,yz:aa,IG:!1}})};f.prototype.y$=function(f){var aa=this,ba={};f.querySelectorAll("pdf-info widget").forEach(function(f){var da=parseInt(f.getAttribute("page"),10)-1;aa.xA(ba,da);ba[da].VV.push(f)});f.querySelectorAll("pdf-info page").forEach(function(f){var da=
parseInt(f.getAttribute("number"),10)-1;aa.xA(ba,da);ba[da].page=f});this.SP(f).forEach(function(f){var da=parseInt(f.getAttribute("page"),10),z=f.getAttribute("name");aa.xA(ba,da);ba[da].$l[z]=f});this.EP(f).forEach(function(f){var da=parseInt(f.getAttribute("page"),10);f=f.textContent;aa.xA(ba,da);ba[da].zO[f]=!0});return ba};f.prototype.xA=function(f,aa){f[aa]||(f[aa]={$l:{},zO:{},VV:[],page:null})};return f}();ca.a=ha},406:function(ha,ca,f){var ba=f(2),aa=f(0);f.n(aa);ha=function(f){function ca(aa){var z=
f.call(this)||this;z.t4=Array.isArray(aa)?aa:[aa];return z}Object(ba.c)(ca,f);ca.prototype.parse=function(){var f=this,z={fo:null,hF:null,zu:{},ca:{}};this.t4.forEach(function(x){z=Object(aa.merge)(z,f.ey(x))});return z};ca.prototype.SP=function(f){var z=[];f.querySelectorAll("add > *").forEach(function(f){z.push(f)});f.querySelectorAll("modify > *").forEach(function(f){z.push(f)});return z};ca.prototype.EP=function(f){return f.querySelectorAll("delete > *")};return ca}(f(392).a);ca.a=ha},407:function(ha,
ca,f){var ba=f(2);ha=function(f){function aa(aa){var ba=f.call(this)||this;ba.u4=aa;return ba}Object(ba.c)(aa,f);aa.prototype.parse=function(){return this.ey(this.u4)};aa.prototype.SP=function(f){return f.querySelectorAll("annots > *")};aa.prototype.EP=function(){return[]};return aa}(f(392).a);ca.a=ha}}]);}).call(this || window)
