/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{366:function(ha,ca,f){f.r(ca);f.d(ca,"ByteRangeRequest",function(){return ja});var ba=f(2),aa=f(0);f.n(aa);var fa=f(1),ea=f(127);ha=f(78);var da=f(206),z=f(61),x=f(57),w=f(205),e=f(141);f=f(320);var h=[],r=[],y=window,ia=function(){return function(){this.nl=1}}(),n;(function(e){e[e.UNSENT=0]="UNSENT";e[e.DONE=4]="DONE"})(n||(n={}));var ja=function(){function f(e,f,h,r){var x=this;this.url=e;this.range=f;this.qf=h;this.withCredentials=
r;this.lY=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);y.Uint8Array&&(this.request.responseType="arraybuffer");r&&(this.request.withCredentials=r);oa.DISABLE_RANGE_HEADER||(Object(aa.isUndefined)(f.stop)?this.request.setRequestHeader("Range","bytes="+f.start):this.request.setRequestHeader("Range",["bytes=",f.start,"-",f.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");h&&Object.keys(h).forEach(function(e){x.request.setRequestHeader(e,
h[e])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=w.a.NOT_STARTED}f.prototype.start=function(e){var f=this,h=this.request;h.onreadystatechange=function(){if(f.aborted)return f.status=w.a.ABORTED,e({code:w.a.ABORTED});if(this.readyState===f.lY.DONE){f.Zz();var n=0===window.document.URL.indexOf("file:///");200===h.status||206===h.status||n&&0===h.status?(n=y.dQ(this),
f.Js(n,e)):(f.status=w.a.ERROR,e({code:f.status,status:f.status}))}};this.request.send(null);this.status=w.a.STARTED};f.prototype.Js=function(e,f){this.status=w.a.SUCCESS;if(f)return f(!1,e)};f.prototype.abort=function(){this.Zz();this.aborted=!0;this.request.abort()};f.prototype.Zz=function(){var n=Object(e.c)(this.url,this.range,r);-1!==n&&r.splice(n,1);if(0<h.length){n=h.shift();var w=new f(n.url,n.range,this.qf,this.withCredentials);n.request=w;r.push(n);w.start(Object(e.d)(n))}};f.prototype.extend=
function(e){var f=Object.assign({},this,e.prototype);f.constructor=e;return f};return f}(),oa=function(f){function n(e,h,n,r,w){n=f.call(this,e,n,r)||this;n.pl={};n.Ey=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.Yv=ja;n.vK=3;n.qf=w||{};return n}Object(ba.c)(n,f);n.prototype.gu=function(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(h){case !1:case x.a.NEVER_CACHE:e=e+n+"_="+Object(aa.uniqueId)();break;case !0:case x.a.CACHE:e=e+n+"_="+f.start+","+(Object(aa.isUndefined)(f.stop)?"":f.stop)}return e};n.prototype.pO=
function(e,f,h,n){void 0===h&&(h={});return new this.Yv(e,f,h,n)};n.prototype.l4=function(e,f,n,w,x){for(var y=0;y<h.length;y++)if(Object(aa.isEqual)(h[y].range,f)&&Object(aa.isEqual)(h[y].url,e))return h[y].rg.push(w),h[y].YA++,null;for(y=0;y<r.length;y++)if(Object(aa.isEqual)(r[y].range,f)&&Object(aa.isEqual)(r[y].url,e))return r[y].rg.push(w),r[y].YA++,null;n={url:e,range:f,Ey:n,rg:[w],YA:1};if(0===h.length&&r.length<this.vK)return r.push(n),n.request=this.pO(e,f,x,this.withCredentials),n;h.push(n);
return null};n.prototype.Vm=function(f,n,w){var x=this.gu(f,n,this.Ey);(f=this.l4(x,n,this.Ey,w,this.qf))&&f.request.start(Object(e.d)(f));return function(){var f=Object(e.c)(x,n,r);if(-1!==f){var w=--r[f].YA;0===w&&r[f].request&&r[f].request.abort()}else f=Object(e.c)(x,n,h),-1!==f&&(w=--h[f].YA,0===w&&h.splice(f,1))}};n.prototype.IP=function(){return{start:-ea.a}};n.prototype.p7=function(){var e=-(ea.a+ea.e);return{start:e-ea.d,end:e}};n.prototype.Or=function(e){var f=this;this.Jy=!0;var h=ea.a;
this.Vm(this.url,this.IP(),function(n,r,w){function x(){var h=f.Md.FP();f.Vm(f.url,h,function(n,r){if(n)return Object(fa.i)("Error loading central directory: "+n),e(n);r=Object(z.a)(r);if(r.length!==h.stop-h.start)return e("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);f.Md.WS(r);f.JE=!0;f.Jy=!1;return e(!1)})}if(n)return Object(fa.i)("Error loading end header: "+n),e(n,r,w);r=Object(z.a)(r);if(r.length!==h)return e("Invalid XOD file: Zip end header data is wrong size!");
try{f.Md=new da.a(r)}catch(ya){return e(ya)}f.Md.J8?f.Vm(f.url,f.p7(),function(h,n){if(h)return Object(fa.i)("Error loading zip64 header: "+h),e(h);n=Object(z.a)(n);f.Md.c9(n);x()}):x()})};n.prototype.aQ=function(e){e(Object.keys(this.Md.xm))};n.prototype.uI=function(e,f){var h=this;if(this.Md.eO(e)){var n=this.Md.Sz(e);if(n in this.pl){var r=this.zh[e];r.Hq=this.pl[n];r.Hq.nl++;r.cancel=r.Hq.cancel}else{var w=this.Md.O5(e),x=this.Vm(this.url,w,function(r,x){r?(Object(fa.i)('Error loading part "'+
e+'": '+r),h.Vm(h.url,w,function(r,x){if(r)return f(r,e);h.$S(x,w,n,e,f)})):h.$S(x,w,n,e,f)}),y=this.zh[e];y&&(y.eV=!0,y.cancel=function(){y.Hq.nl--;0===y.Hq.nl&&(x(),delete h.pl[n])},this.pl[n]=new ia(n),y.Hq=this.pl[n],y.Hq.cancel=y.cancel)}}else delete this.zh[e],f(Error('File not found: "'+e+'"'),e)};n.prototype.$S=function(e,f,h,n,r){if(e.length!==f.stop-f.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.pl[h])return;n=this.pl[h].nl;for(var w=f.yp.length,x=0;x<w;++x){var y=f.yp[x];
r(!1,y.up,e["string"===typeof e?"substring":"subarray"](y.start,y.stop),this.Md.YQ(y.up));y.up in this.zh&&delete this.zh[y.up]}}while(n!==this.pl[h].nl);delete this.pl[h]}};n.DISABLE_RANGE_HEADER=!1;n.vK=3;return n}(ha.a);(function(e){function f(f,h,n){var r=e.call(this)||this,w;for(w in f)r[w]=f[w];r.Dia=f;r.startOffset=h;r.endOffset=n;r.pO=function(e,h,n,w){Object(aa.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);e=r.gu(r.url,h,r.Ey);
return new f.Yv(e,h,n,w)};return r}Object(ba.c)(f,e);return f})(oa);Object(f.a)(oa);Object(f.b)(oa);ca["default"]=oa}}]);}).call(this || window)
