/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{380:function(ha,ca,f){function ba(e){e.Ja();e.advance();var f=e.current.textContent;e.$a();return f}function aa(e){var f=[];for(e.Ja();e.advance();){var h=e.Na();"field"===h?f.push(String(e.da("name"))):Object(n.i)("unrecognised field list element: "+h)}e.$a();return f}function fa(e,f){return f?"false"!==e:"true"===e}function ea(e,f){var h=e.Na();switch(h){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.da("uri")};case "goto":h=null;e.Ja();if(e.advance()){var r=e.da("fit");h={page:e.da("page"),fit:r};if("0"===h.page)Object(n.i)("null page encountered in dest");else switch(f=f(Number(h.page)),r){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.qa({x:0,y:e.da("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.qa({x:e.da("left")||0,y:0}).x;break;case "FitR":r=f.qa({x:e.da("left")||0,y:e.da("top")||0});f=f.qa({x:e.da("right")||0,y:e.da("bottom")||0});
f=new pa.d(r.x,r.y,f.x,f.y);h.top=f.ja;h.left=f.ma;h.bottom=f.ka;h.right=f.na;break;case "XYZ":r=f.qa({x:e.da("left")||0,y:e.da("top")||0});h.top=r.y;h.left=r.x;h.zoom=e.da("zoom")||0;break;default:Object(n.i)("unknown dest fit: "+r)}h={name:"GoTo",dest:h}}else Object(n.i)("missing dest in GoTo action");e.$a();return h;case "submit-form":h={name:"SubmitForm",url:e.da("url"),format:e.da("format"),method:e.da("method")||"POST",exclude:fa(e.da("exclude"),!1)};f=e.da("flags");h.flags=f?f.split(" "):[];
for(e.Ja();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=aa(e);break;default:Object(n.i)("unrecognised submit-form child: "+f)}e.$a();return h;case "reset-form":h={name:"ResetForm",exclude:fa(e.da("exclude"),!1)};for(e.Ja();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=aa(e);break;default:Object(n.i)("unrecognised reset-form child: "+f)}e.$a();return h;case "hide":h={name:"Hide",hide:fa(e.da("hide"),!0)};for(e.Ja();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=aa(e);break;
default:Object(n.i)("unrecognised hide child: "+f)}e.$a();return h;case "named":return{name:"Named",action:e.da("name")};default:Object(n.i)("Encountered unexpected action type: "+h)}return null}function da(e,f,h){var r={};for(e.Ja();e.advance();){var w=e.Na();switch(w){case "action":w=e.da("trigger");if(f?-1!==f.indexOf(w):1){r[w]=[];for(e.Ja();e.advance();){var x=ea(e,h);Object(ja.isNull)(x)||r[w].push(x)}e.$a()}else Object(n.i)("encountered unexpected trigger on field: "+w);break;default:Object(n.i)("encountered unknown action child: "+
w)}}e.$a();return r}function z(e){return new na.a(e.da("r")||0,e.da("g")||0,e.da("b")||0,e.da("a")||1)}function x(e,f){var h=e.da("name"),r=e.da("type")||"Type1",w=e.da("size"),x=f.qa({x:0,y:0});w=f.qa({x:Number(w),y:0});f=x.x-w.x;x=x.y-w.y;h={name:h,type:r,size:Math.sqrt(f*f+x*x)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.Ja();e.advance();)switch(r=e.Na(),r){case "stroke-color":h.strokeColor=z(e);break;case "fill-color":h.fillColor=z(e);break;default:Object(n.i)("unrecognised font child: "+
r)}e.$a();return h}function w(e){return{value:e.da("value"),displayValue:e.da("display-value")||void 0}}function e(e){var f=[];for(e.Ja();e.advance();){var h=e.Na();switch(h){case "option":f.push(w(e));break;default:Object(n.i)("unrecognised options child: "+h)}}e.$a();return f}function h(f,h){var r=f.da("name"),w={type:f.da("type"),quadding:f.da("quadding")||"Left-justified",maxLen:f.da("max-len")||-1},y=f.da("flags");Object(ja.isString)(y)&&(w.flags=y.split(" "));for(f.Ja();f.advance();)switch(y=
f.Na(),y){case "actions":w.actions=da(f,["C","F","K","V"],function(){return h});break;case "default-value":w.defaultValue=ba(f);break;case "font":w.font=x(f,h);break;case "options":w.options=e(f);break;default:Object(n.i)("unknown field child: "+y)}f.$a();return new window.Annotations.fa.ra(r,w)}function r(e,f){switch(e.type){case "Tx":try{if(Object(wa.c)(e.actions))return new oa.a.DatePickerWidgetAnnotation(e,f)}catch(ma){Object(n.i)(ma)}return new oa.a.TextWidgetAnnotation(e,f);case "Ch":return e.flags.get(xa.WidgetFlags.COMBO)?
new oa.a.ChoiceWidgetAnnotation(e,f):new oa.a.ListWidgetAnnotation(e,f);case "Btn":return e.flags.get(xa.WidgetFlags.PUSH_BUTTON)?new oa.a.PushButtonWidgetAnnotation(e,f):e.flags.get(xa.WidgetFlags.RADIO)?new oa.a.RadioButtonWidgetAnnotation(e,f):new oa.a.CheckButtonWidgetAnnotation(e,f);case "Sig":return new oa.a.SignatureWidgetAnnotation(e,f);default:Object(n.i)("Unrecognised field type: "+e.type)}return null}function y(e,f){var h={number:e.da("number")};for(e.Ja();e.advance();){var r=e.Na();switch(r){case "actions":h.actions=
da(e,["O","C"],f);break;default:Object(n.i)("unrecognised page child: "+r)}}e.$a();return h}function ia(e,f,w,ba){var ea=[],ca={};e.Ja();var fa=[],ha={},ja=[];Object(ka.a)(function(){if(e.advance()){var w=e.Na();switch(w){case "calculation-order":fa="calculation-order"===e.Na()?aa(e):[];break;case "document-actions":ha=da(e,["Init","Open"],f);break;case "pages":w=[];for(e.Ja();e.advance();){var ba=e.Na();switch(ba){case "page":w.push(y(e,f));break;default:Object(n.i)("unrecognised page child: "+ba)}}e.$a();
ja=w;break;case "field":ba=h(e,f(1));ca[ba.name]=ba;break;case "widget":w={border:{style:"Solid",width:1},backgroundColor:[],fieldName:e.da("field"),page:e.da("page"),index:e.da("index")||0,rotation:e.da("rotation")||0,flags:[],isImporting:!0};(ba=e.da("appearance"))&&(w.appearance=ba);(ba=e.da("flags"))&&(w.flags=ba.split(" "));for(e.Ja();e.advance();)switch(ba=e.Na(),ba){case "rect":var ia=e,ma=f(Number(w.page));ba=ma.qa({x:ia.da("x1")||0,y:ia.da("y1")||0});ia=ma.qa({x:ia.da("x2")||0,y:ia.da("y2")||
0});ba=new pa.d(ba.x,ba.y,ia.x,ia.y);ba.normalize();w.rect={x1:ba.x1,y1:ba.y1,x2:ba.x2,y2:ba.y2};break;case "border":ba=e;ia={style:ba.da("style")||"Solid",width:ba.da("width")||1,color:[0,0,0]};for(ba.Ja();ba.advance();)switch(ma=ba.Na(),ma){case "color":ia.color=z(ba);break;default:Object(n.i)("unrecognised border child: "+ma)}ba.$a();w.border=ia;break;case "background-color":w.backgroundColor=z(e);break;case "actions":w.actions=da(e,"E X D U Fo Bl PO PC PV PI".split(" "),f);break;case "appearances":ba=
e;ia=Object(wa.b)(w,"appearances");for(ba.Ja();ba.advance();)if(ma=ba.Na(),"appearance"===ma){ma=ba.da("name");var ka=Object(wa.b)(ia,ma);ma=ba;for(ma.Ja();ma.advance();){var la=ma.Na();switch(la){case "Normal":Object(wa.b)(ka,"Normal").data=ma.current.textContent;break;default:Object(n.i)("unexpected appearance state: ",la)}}ma.$a()}else Object(n.i)("unexpected appearances child: "+ma);ba.$a();break;case "extra":ba=e;ia=f;ma={};for(ba.Ja();ba.advance();)switch(ka=ba.Na(),ka){case "font":ma.font=
x(ba,ia(1));break;default:Object(n.i)("unrecognised extra child: "+ka)}ba.$a();ba=ma;ba.font&&(w.font=ba.font);break;case "captions":ia=e;ba={};(ma=ia.da("Normal"))&&(ba.Normal=ma);(ma=ia.da("Rollover"))&&(ba.Rollover=ma);(ia=ia.da("Down"))&&(ba.Down=ia);w.captions=ba;break;default:Object(n.i)("unrecognised widget child: "+ba)}e.$a();(ba=ca[w.fieldName])?(w=r(ba,w),ea.push(w)):Object(n.i)("ignoring widget with no corresponding field data: "+w.fieldName);break;default:Object(n.i)("Unknown element encountered in PDFInfo: "+
w)}return!0}return!1},function(){e.$a();w({calculationOrder:fa,widgets:ea,fields:ca,documentActions:ha,pages:ja,custom:[]})},ba)}f.r(ca);f.d(ca,"parse",function(){return ia});var n=f(1),ja=f(0);f.n(ja);var oa=f(99),pa=f(4),na=f(7),ka=f(26),wa=f(85),xa=f(13)}}]);}).call(this || window)
