/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{374:function(ha,ca,f){f.r(ca);var ba=f(2),aa=f(0);f.n(aa);var fa=f(1),ea=f(127);ha=f(44);var da=f(78),z=f(206),x=f(57),w=f(205);f=f(320);var e=window,h=function(){function f(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(f){case x.a.NEVER_CACHE:this.url=e+n+"_="+Object(aa.uniqueId)();break;default:this.url=e}this.qf=h;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=w.a.NOT_STARTED}f.prototype.start=function(e,h){var n=this,r=this,x=this.request,y;r.rv=0;e&&Object.keys(e).forEach(function(f){n.request.setRequestHeader(f,e[f])});h&&(this.request.withCredentials=h);this.uB=setInterval(function(){var e=0===window.document.URL.indexOf("file:///");e=200===x.status||e&&0===x.status;
if(x.readyState!==w.b.DONE||e){try{x.responseText}catch(xa){return}r.rv<x.responseText.length&&(y=r.oaa())&&r.trigger(f.Events.DATA,[y]);0===x.readyState&&(clearInterval(r.uB),r.trigger(f.Events.DONE))}else clearInterval(r.uB),r.trigger(f.Events.DONE,["Error received return status "+x.status])},1E3);this.request.send(null);this.status=w.a.STARTED};f.prototype.oaa=function(){var h=this.request,r=h.responseText;if(0!==r.length)if(this.rv===r.length)clearInterval(this.uB),this.trigger(f.Events.DONE);
else return r=Math.min(this.rv+3E6,r.length),h=e.dQ(h,this.rv,!0,r),this.rv=r,h};f.prototype.abort=function(){clearInterval(this.uB);var e=this;this.request.onreadystatechange=function(){Object(fa.i)("StreamingRequest aborted");e.status=w.a.ABORTED;return e.trigger(f.Events.ABORTED)};this.request.abort()};f.prototype.finish=function(){var e=this;this.request.onreadystatechange=function(){e.status=w.a.SUCCESS;return e.trigger(f.Events.DONE)};this.request.abort()};f.Events={DONE:"done",DATA:"data",
ABORTED:"aborted"};return f}();Object(ha.a)(h);var r;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(r||(r={}));var y=function(e){function f(){var f=e.call(this)||this;f.buffer="";f.state=r.LOCAL_HEADER;f.CJ=4;f.al=null;f.Sr=ea.c;f.xm={};return f}Object(ba.c)(f,e);f.prototype.iaa=function(e){var h;for(e=this.buffer+e;e.length>=this.Sr;)switch(this.state){case r.LOCAL_HEADER:this.al=h=this.saa(e.slice(0,this.Sr));if(h.Cs!==ea.g)throw Error("Wrong signature in local header: "+
h.Cs);e=e.slice(this.Sr);this.state=r.FILE;this.Sr=h.AE+h.lp+h.yu+this.CJ;this.trigger(f.Events.HEADER,[h]);break;case r.FILE:this.al.name=e.slice(0,this.al.lp);this.xm[this.al.name]=this.al;h=this.Sr-this.CJ;var n=e.slice(this.al.lp+this.al.yu,h);this.trigger(f.Events.FILE,[this.al.name,n,this.al.QE]);e=e.slice(h);if(e.slice(0,this.CJ)===ea.h)this.state=r.LOCAL_HEADER,this.Sr=ea.c;else return this.state=r.CENTRAL_DIR,!0}this.buffer=e;return!1};f.Events={HEADER:"header",FILE:"file"};return f}(z.a);
Object(ha.a)(y);ha=function(e){function f(f,n,r,w,x){r=e.call(this,f,r,w)||this;r.url=f;r.stream=new h(f,n);r.Md=new y;r.JS=window.createPromiseCapability();r.fT={};r.qf=x;return r}Object(ba.c)(f,e);f.prototype.ew=function(e){var f=this;this.request([this.Ni,this.Xj,this.Mi]);this.stream.addEventListener(h.Events.DATA,function(h){try{if(f.Md.iaa(h))return f.stream.finish()}catch(na){throw f.stream.abort(),f.vu(na),e(na),na;}});this.stream.addEventListener(h.Events.DONE,function(h){f.Q$=!0;f.JS.resolve();
h&&(f.vu(h),e(h))});this.Md.addEventListener(y.Events.HEADER,Object(aa.bind)(this.eT,this));this.Md.addEventListener(y.Events.FILE,Object(aa.bind)(this.Iaa,this));return this.stream.start(this.qf,this.withCredentials)};f.prototype.aQ=function(e){var f=this;this.JS.promise.then(function(){e(Object.keys(f.Md.xm))})};f.prototype.an=function(){return!0};f.prototype.request=function(e){var f=this;this.Q$&&e.forEach(function(e){f.fT[e]||f.Nea(e)})};f.prototype.eT=function(){};f.prototype.abort=function(){this.stream&&
this.stream.abort()};f.prototype.Nea=function(e){this.trigger(da.a.Events.PART_READY,[{bb:e,error:"Requested part not found",Wh:!1,Nf:!1}])};f.prototype.Iaa=function(e,f,h){this.fT[e]=!0;this.trigger(da.a.Events.PART_READY,[{bb:e,data:f,Wh:!1,Nf:!1,error:null,ad:h}])};return f}(da.a);Object(f.a)(ha);Object(f.b)(ha);ca["default"]=ha}}]);}).call(this || window)
